# 公共配置文件

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME:user-center-backend}
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/user_centre}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD}
  # session 失效时间
  session:
    timeout: 86400
  redis:
    # 默认6379
    port: ${REDIS_PORT:6379}
    host: localhost
    #database: 0
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: AUTO # 关闭雪花算法（js大数丢失精度）
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
springdoc:
  api-docs:
    enabled: true
    # path: /v3/api-docs
  swagger-ui:
    enabled: true

